### PR TITLE
Remove dashboard page

### PR DESCRIPTION
**Pull request by mybits**
### ISSUE/TICKET NUMBER
Remove Dashboard page

### Describe the changes
Dashboard page was found to be redundant in the current flow.  This PR is to:
- remove a dashboard page with all relevant code
- redirect a user after logging in to a tasks list page  (Act page).

This PR also brings changes into an upgrade of psycopg2 as the previous version didn't support postgres 10.

### Screenshots (if appropriate)
n/a

### Questions or comments (if any)
n/a

### CODE REVIEW

**Comment by mybits** [comment]
Thanks for the review @gnocchi2815!
I've removed templates/dashboard in this commit: 7e8d5d98a5e8e22e7fc98947d9e7481755553873

now the tasks templates sit in act folder so the structure is `ocdaction/templates/act/` instead of previous `ocdaction/templates/dashboard/act/`

But maybe I've missed something 🤔

**Comment by mybits** [comment]
Oops, closed by accident (those two buttons should not sit so close to each other...)

**Comment by gnocchi2815** [comment]
The folder still shows (but empty) in the folder structure of the project.

**Comment by mybits** [comment]
Can you please point me out to it (screenshot would be the best), as I can't see it neither locally nor in a github. This is the screenshot from the `remove-dashboard-pag` branch of `templates` folder structure:

screen shot 2017-11-03 at 19 55 40

**Comment by gnocchi2815** [comment]
Ok this must just be a local thing for me, I can still see it in my IDE 
screen shot 2017-11-04 at 13 04 09

**Comment by mybits** [comment]
@gnocchi2815 that's strange indeed. I'll merge the PR and please check later if you see it on the pulled master as well

**Pull request merged**
