### PR TITLE
Do task all anxiety levels must be populated for task to be completed…

### PR DESCRIPTION
**Pull request by lmash**
…, error message added

### ISSUE/TICKET NUMBER
Trello ticket: Fill in all anxiety levels - validation

### Describe the changes
When completing a task displays error message (at the top of the form fields) if any of the anxiety levels are not populated.

### Screenshots (if appropriate)
 - After
screen shot 2017-08-12 at 17 27 37

### Questions or comments (if any)
Error message displayed per field if not populated

### CODE REVIEW

**Comment by lmash** [comment]
@gnocchi2815 agreed much easier to set at the model level - I don't have an overall idea of how the validation should be handled (i.e. at DB level / in the app), happy to proceed either way.

**Comment by gnocchi2815** [comment]
@lmash logically I think it should be validated at the model level if as per my previous message there is never any need to save the scores part way through - @mybits do you have a view here?

**Comment by mybits** [comment]
Hi @gnocchi2815 and @lmash :) yes I think as well the validation should happen at the model level.

**Comment by lmash** [comment]
thanks @gnocchi2815 and @mybits  - I'll proceed with that change..

**Comment by mybits** [comment]
👍 :shipit:

**Comment by nbhatt08** [comment]
Hello all,

Can you please get me out of this mailing list? Unfortunately due to time, I won't be able to contribute to any of the projects. 

Thanks,
Nikita 

Sent from my iPhone

On 14 Aug 2017, at 5:25 pm, Paula Stepinska <notifications@github.com> wrote:

👍

**Comment by mybits** [comment]
Hello @nbhatt08 there's no mailing list but your github account notifications that you need to change by your own.

**Pull request merged**
