### PR TITLE
changed the images to new urls, as issue 48

### PR DESCRIPTION
**Pull request by HC27**
### ISSUE/TICKET NUMBER
issue 48

### Describe the changes
updated image links to new URLs
### Screenshots (if appropriate)
Add "n/a" if nothing to attach
 - Before
 - After

### Questions or comments (if any)
Add "n/a" if nothing to say

### CODE REVIEW

**Comment by lili2311** [comment]
Hi, we have added MEDIA URL in another PR so please can we use that? Please merge latest master into your branch and resolve the merge conflics you have but keep the MEDIA URL implementation rather than 100% hardcoded urls thanks!

**Comment by mybits** [comment]
Hi @HC27 are you still working on this please?

**Comment by HC27** [comment]
Yes sorry, haven't had chance to look at it for a while, I believe it is
finished though

On 5 Apr 2017 11:00 p.m., "Paula Stepinska" <notifications@github.com>
wrote:

Hi @HC27 <https://github.com/HC27> are you still working on this please?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/womenhackfornonprofits/ocdaction/pull/68#issuecomment-292010004>,
or mute the thread

**Comment by lili2311** [comment]
@HC27 you have some merge conflics please can you solve so we can get this merged?

**Comment by HC27** [comment]
Sorry! Yep I'll get that sorted tonight
Hannah

**Comment by mybits** [comment]
Hi @lili2311 is it maybe worth to create a new PR based on that issue so we're not blocked?

**Comment by lili2311** [comment]
What do you mean? We can merge this one but the conflics have to be resolved. If you need a hand resolving them please let me know

**Comment by HC27** [comment]
hi sorry it's taken so long for me to look at this, i've ended up being away without my laptop. I'm a little confused though, it seems the links have already been updated to use MEDIA URL so there's nothing to be done in this commit?

**Comment by mybits** [comment]
Closing this PR as the changes have been already implemented

**Pull request closed without merging**
