### PR TITLE
Add tests app and initial test checking 1+1

### PR DESCRIPTION
**Pull request by lmash**
### ISSUE/TICKET NUMBER
Add pytest and configure

### Describe the changes
Added a new tests app with a simple test

### Screenshots (if appropriate)
n/a (tests run via the backend)

### Questions or comments (if any)
Is a separate test app required? Simply having a file named test_*.py in an existing app would ensure it gets included when pytest is run?

### CODE REVIEW

**Comment by lili2311** [comment]
It should be an app yes but we can delete the view, model and admin file as we do not need it. But could do with a README here:
```# OCD Action Test Suite

## Django App

Our tests package: `ocdaction.tests` is a valid Django app and should
be installed in Django's `INSTALLED_APPS` setting during test suite runs.

## Test Placement

The tests folder is laid out in such a way that it mirrors as closely as
possible the actual codebase.

### Example

Here is an example to show you how new test files should be placed:

    ocdaction/apps/profiles/example_file.py

is tested at:

    wound_care_buddy/tests/apps/profiles/test_example_file.py```

**Comment by lili2311** [comment]
And does the test run and pass on the backend?

**Comment by lmash** [comment]
ok, makes sense now to have as separate. I've included all suggested changes, removed the migrations folder as well. I did not add to INSTALLED_APPS as yet..
And yes - the initial test passes, to make it fail either change 
    assert add(1, 1) == 2
to say
    assert add(1, 1) == 3
and run pytest ocdaction
you'll then see the test fail

**Comment by lili2311** [comment]
okies great we can have a separate PR for a separate settings file and adding to installed apps 👍

**Pull request merged**
